server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.1.129


aliyun:
  sms:
    accessKeyId: xxx
    accessKeySecret: xxx
    template_code: xxx
    sign_name: xxx